"""message

Revision ID: 34184d857d25
Revises: 6d51c9c424a1
Create Date: 2020-10-13 11:05:17.061057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34184d857d25'
down_revision = '6d51c9c424a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fin_asset_attachment', sa.Column('url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fin_asset_attachment', 'url')
    # ### end Alembic commands ###
